# Generated by Django 4.2.30 on 2026-06-15 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0002_laborder_testmaster_labreport_laborderitem'),
        ('people', '0001_initial'),
        ('prescriptions', '0002_prescription_doctor_prescription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('specialist_type', models.CharField(help_text='The type of specialist the patient is referred to (e.g. Cardiologist, Obstetrician).', max_length=100)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', help_text='Urgency level of this referral.', max_length=20)),
                ('reason', models.TextField(help_text='The core clinical reason/indication for referral.')),
                ('referral_note', models.TextField(blank=True, help_text='Additional referral instructions or notes for the specialist.')),
                ('attached_prescriptions', models.ManyToManyField(blank=True, help_text='Prescriptions attached to this referral.', related_name='stitch_files', to='prescriptions.prescription')),
                ('attached_reports', models.ManyToManyField(blank=True, help_text='Lab reports attached to this referral.', related_name='stitch_files', to='laboratory.labreport')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this referral/stitch record belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='stitch_files', to='people.patient')),
            ],
            options={
                'verbose_name': 'Stitch File',
                'verbose_name_plural': 'Stitch Files',
                'db_table': 'stitch_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
