#!/usr/bin/env pwsh
# ─────────────────────────────────────────────────────────────────
# MotherCare — One-Click Startup (Windows PowerShell)
# Run this once on any new laptop. No Docker needed.
# Usage:  .\START.ps1
# ─────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

Write-Host ""
Write-Host "╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║     MotherCare — Startup Script              ║" -ForegroundColor Cyan
Write-Host "║     Shakuntala Hospital Management System    ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check prerequisites ────────────────────────────────────────
Write-Host "► Checking prerequisites..." -ForegroundColor Yellow

if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    Write-Host "  ✗ Python not found. Install Python 3.11+ from https://python.org" -ForegroundColor Red
    exit 1
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Host "  ✗ Node.js not found. Install Node.js 18+ from https://nodejs.org" -ForegroundColor Red
    exit 1
}

# Install uv if missing
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Host "  Installing uv (Python package manager)..." -ForegroundColor Yellow
    irm https://astral.sh/uv/install.ps1 | iex
    $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"
}

Write-Host "  ✓ All prerequisites OK" -ForegroundColor Green

# ── 2. Backend Setup ──────────────────────────────────────────────
Write-Host ""
Write-Host "► Setting up Backend (SQLite — no Docker needed)..." -ForegroundColor Yellow

$backend = Join-Path $root "backend"
Set-Location $backend

# Create .env if missing (SQLite mode — no secrets needed)
if (-not (Test-Path ".env")) {
    Write-Host "  Creating .env file..." -ForegroundColor Yellow
    @"
# Auto-generated by START.ps1 — SQLite mode (no Docker needed)
DEBUG=True
SECRET_KEY=dev-only-insecure-key-change-in-production-123456
ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
HOSPITAL_CODE=SH-MAT-2024
SESSION_TOKEN_EXPIRY_HOURS=8
SESSION_REMEMBER_ME_EXPIRY_HOURS=720
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
"@ | Out-File -FilePath ".env" -Encoding utf8
    Write-Host "  ✓ .env created" -ForegroundColor Green
}

# Install Python dependencies
Write-Host "  Installing Python dependencies..." -ForegroundColor Yellow
uv sync

# Run migrations with SQLite settings
Write-Host "  Running database migrations..." -ForegroundColor Yellow
uv run python manage.py migrate --settings=config.settings.sqlite

# Seed users and data
Write-Host "  Seeding users and hospital data..." -ForegroundColor Yellow
uv run python manage.py seed_data --settings=config.settings.sqlite

Write-Host "  ✓ Backend ready!" -ForegroundColor Green

# ── 3. Frontend Setup ─────────────────────────────────────────────
Write-Host ""
Write-Host "► Setting up Frontend..." -ForegroundColor Yellow

$frontend = Join-Path $root "frontend"
Set-Location $frontend

# Create frontend .env if missing
if (-not (Test-Path ".env")) {
    Write-Host "  Creating frontend .env..." -ForegroundColor Yellow
    "VITE_API_URL=http://localhost:8000/api/v1" | Out-File -FilePath ".env" -Encoding utf8
    Write-Host "  ✓ Frontend .env created" -ForegroundColor Green
}

# Install npm packages
Write-Host "  Installing npm packages..." -ForegroundColor Yellow
npm install

Write-Host "  ✓ Frontend ready!" -ForegroundColor Green

# ── 4. Done! ──────────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✓ Setup Complete! Open 2 terminals:         ║" -ForegroundColor Green
Write-Host "║                                              ║" -ForegroundColor Green
Write-Host "║  Terminal 1 (Backend):                       ║" -ForegroundColor Green
Write-Host "║    cd backend                                ║" -ForegroundColor Green
Write-Host "║    uv run python manage.py runserver \        ║" -ForegroundColor Green
Write-Host "║      --settings=config.settings.sqlite       ║" -ForegroundColor Green
Write-Host "║                                              ║" -ForegroundColor Green
Write-Host "║  Terminal 2 (Frontend):                      ║" -ForegroundColor Green
Write-Host "║    cd frontend                               ║" -ForegroundColor Green
Write-Host "║    npm run dev                               ║" -ForegroundColor Green
Write-Host "║                                              ║" -ForegroundColor Green
Write-Host "║  Open: http://localhost:5173                  ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Login Credentials:" -ForegroundColor Cyan
Write-Host "  ┌─────────────┬──────────────┬──────────────────┐"
Write-Host "  │ Username    │ Password     │ Role             │"
Write-Host "  ├─────────────┼──────────────┼──────────────────┤"
Write-Host "  │ admin       │ admin@#123   │ System Admin     │"
Write-Host "  │ vinit       │ vinit@#123   │ Doctor           │"
Write-Host "  │ viraj       │ viraj@#123   │ Lab Tech         │"
Write-Host "  │ chinmay     │ chinmay@#123 │ Pharmacist       │"
Write-Host "  └─────────────┴──────────────┴──────────────────┘"
Write-Host ""

Set-Location $root
