# Generated by Django 4.2.30 on 2026-06-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('locale', models.CharField(default='en-IN', max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('department_type', models.CharField(choices=[('Obstetrics', 'Obstetrics'), ('Pediatrics', 'Pediatrics'), ('Nursing', 'Nursing'), ('Admin', 'Admin'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('ICU', 'ICU'), ('HR', 'HR'), ('Other', 'Other')], default='Other', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
    ]
