# Generated by Django 4.2.30 on 2026-06-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('hospital_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_staff',
            field=models.ForeignKey(blank=True, help_text='Department head (optional, nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='people.staff'),
        ),
    ]
