# Generated by Django 4.2.30 on 2026-06-07 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('appointment_datetime', models.DateTimeField(db_index=True, help_text='Date and time of the appointment (UTC stored, displayed in local timezone).')),
                ('appointment_type', models.CharField(choices=[('new_patient', 'New Patient'), ('follow_up', 'Follow-up'), ('anc', 'Antenatal Care (ANC)'), ('emergency', 'Emergency'), ('scan', 'Scan'), ('lab_review', 'Lab Review'), ('gdm_screen', 'GDM Screening'), ('ultrasound', 'Ultrasound')], default='new_patient', help_text='Type of appointment: new_patient | follow_up | anc | emergency | ...', max_length=20)),
                ('token_number', models.PositiveSmallIntegerField(help_text='Sequential token per doctor per day starting at 101 (BR-APPT-03). Unique per (doctor, date, token). Retired tokens are never reassigned (BR-APPT-12).')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', help_text='Appointment status. Transitions are one-directional (BR-APPT-07).', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Booking notes / reason for visit.')),
                ('booked_by', models.ForeignKey(blank=True, help_text='Staff user who booked this appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor this appointment is booked with.', on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='people.doctor')),
                ('patient', models.ForeignKey(help_text='Patient this appointment belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='people.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointment',
                'ordering': ['appointment_datetime'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_appt_patient_status'), models.Index(fields=['doctor', 'appointment_datetime'], name='idx_appt_doctor_dt'), models.Index(fields=['status', 'appointment_datetime'], name='idx_appt_status_dt'), models.Index(fields=['is_deleted'], name='idx_appt_is_deleted')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('doctor', 'token_number'), name='uq_appointment_doctor_token_date'),
        ),
    ]
