# Generated by Django 4.2.30 on 2026-06-07 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the consultation started (server time).')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the consultation ended. Set on completion. [DB CHECK: end_time > start_time]', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', help_text='Consultation status: in_progress | completed | cancelled', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's clinical notes (SOAP, narrative, or structured). Immutable after completion.")),
                ('diagnosis', models.TextField(blank=True, help_text='Primary and secondary diagnoses from this consultation.')),
                ('follow_up_datetime', models.DateTimeField(blank=True, help_text='Requested follow-up datetime. When set, POST /follow-up creates a new Appointment. BR-CONS-10: Only one follow-up per consultation.', null=True)),
                ('appointment', models.OneToOneField(help_text='Source appointment. UNIQUE enforces one-consultation-per-appointment (BR-CONS-01). RESTRICT prevents deleting appointment with existing consultation.', on_delete=django.db.models.deletion.RESTRICT, related_name='consultation', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor — copied from appointment at creation, immutable after.', on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='people.doctor')),
                ('patient', models.ForeignKey(help_text='Patient — copied from appointment at creation, immutable after.', on_delete=django.db.models.deletion.RESTRICT, related_name='consultations', to='people.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultation',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_cons_patient_status'), models.Index(fields=['doctor', 'start_time'], name='idx_cons_doctor_start'), models.Index(fields=['status', 'start_time'], name='idx_cons_status_start'), models.Index(fields=['is_deleted'], name='idx_cons_is_deleted')],
            },
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.CheckConstraint(check=models.Q(('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='chk_consultation_end_after_start'),
        ),
    ]
