# Generated by Django 4.2.30 on 2026-06-07 08:12

from django.conf import settings

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('lmp', models.DateField(help_text='Last Menstrual Period date. Used to calculate EDD and current_week.')),
                ('edd', models.DateField(help_text='Estimated Due Date. Must be after LMP. [DB CHECK: edd > lmp]')),
                ('current_week', models.PositiveSmallIntegerField(default=1, help_text='Current gestational week (1–45). Auto-calculated from LMP. [DB CHECK: 1–45]', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('trimester', models.PositiveSmallIntegerField(choices=[(1, 'First Trimester (Weeks 1–13)'), (2, 'Second Trimester (Weeks 14–27)'), (3, 'Third Trimester (Weeks 28–42)')], default=1, help_text='Current trimester (1, 2, or 3). Auto-derived from current_week.')),
                ('risk_status', models.CharField(choices=[('normal', 'Normal'), ('high_risk', 'High Risk'), ('critical', 'Critical')], db_index=True, default='normal', help_text='Clinical risk classification. normal | high_risk | critical', max_length=20)),
                ('gravida', models.PositiveSmallIntegerField(default=1, help_text='Total number of pregnancies including this one (G in GPAL notation).')),
                ('para', models.PositiveSmallIntegerField(default=0, help_text='Number of previous deliveries after 20 weeks (P in GPAL notation).')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Pre-existing chronic conditions relevant to this pregnancy (free text).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='TRUE = current active pregnancy. FALSE = concluded / historical.')),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='Doctor assigned to manage this pregnancy. RESTRICT protects data integrity.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_pregnancies', to='people.doctor')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this pregnancy belongs to. RESTRICT — cannot delete patient with pregnancies.', on_delete=django.db.models.deletion.RESTRICT, related_name='pregnancies', to='people.patient')),
            ],
            options={
                'verbose_name': 'Pregnancy',
                'verbose_name_plural': 'Pregnancies',
                'db_table': 'pregnancy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('dietary_protocol', models.TextField(blank=True, help_text="High-level dietary protocol description (e.g. 'Low-GI diet recommended for GDM risk').")),
                ('dietary_items', models.JSONField(blank=True, default=list, help_text='JSONB array of specific dietary items/recommendations.')),
                ('daily_precautions', models.JSONField(blank=True, default=list, help_text='JSONB array of daily precautions and activity guidelines.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.OneToOneField(help_text='Parent pregnancy. CASCADE — wellness plan deleted with pregnancy. UNIQUE enforces 1:1.', on_delete=django.db.models.deletion.CASCADE, related_name='wellness_plan', to='pregnancy.pregnancy')),
            ],
            options={
                'verbose_name': 'Wellness Plan',
                'verbose_name_plural': 'Wellness Plans',
                'db_table': 'wellness_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AncVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('visit_date', models.DateField(help_text='Date of the ANC visit.')),
                ('week_at_visit', models.PositiveSmallIntegerField(help_text='Gestational week at the time of this visit (1–45).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('visit_type', models.CharField(choices=[('routine', 'Routine ANC'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up'), ('gdm_screen', 'GDM Screening'), ('ultrasound', 'Ultrasound'), ('lab_review', 'Lab Review')], default='routine', help_text='Type of ANC visit.', max_length=20)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, help_text='Systolic blood pressure (mmHg). Normal range: 90–140.', null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(200)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, help_text='Diastolic blood pressure (mmHg). Normal range: 60–90.', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(140)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Maternal weight in kilograms.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('fhr_bpm', models.PositiveSmallIntegerField(blank=True, help_text='Foetal Heart Rate in beats per minute. Normal: 120–160.', null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(200)])),
                ('glucose_mgdl', models.DecimalField(blank=True, decimal_places=2, help_text='Fasting or random blood glucose (mg/dL). GDM screening.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(600)])),
                ('notes', models.TextField(blank=True, help_text='Clinical notes from this ANC visit.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor who conducted this visit. RESTRICT protects data integrity.', on_delete=django.db.models.deletion.RESTRICT, related_name='anc_visits_conducted', to='people.doctor')),
                ('pregnancy', models.ForeignKey(help_text='Parent pregnancy. RESTRICT — do not delete pregnancy with ANC visits.', on_delete=django.db.models.deletion.RESTRICT, related_name='anc_visits', to='pregnancy.pregnancy')),
            ],
            options={
                'verbose_name': 'ANC Visit',
                'verbose_name_plural': 'ANC Visits',
                'db_table': 'anc_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('vaccine_name', models.CharField(help_text="Name of the vaccine (e.g. 'TT Dose 1', 'Influenza', 'Hepatitis B').", max_length=200)),
                ('status', models.CharField(choices=[('due', 'Due'), ('administered', 'Administered'), ('not_required', 'Not Required'), ('skipped', 'Skipped')], db_index=True, default='due', help_text='Vaccination status: due | administered | not_required | skipped', max_length=20)),
                ('due_week_start', models.PositiveSmallIntegerField(blank=True, help_text='Earliest gestational week this vaccine is due.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('due_week_end', models.PositiveSmallIntegerField(blank=True, help_text='Latest gestational week this vaccine is due.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('administered_date', models.DateField(blank=True, help_text="Date vaccine was administered. Required when status = 'administered'.", null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for skip, batch number, or any other notes.')),
                ('administered_by', models.ForeignKey(blank=True, help_text='Doctor who administered this vaccine. SET NULL if doctor record deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternal_vaccinations_administered', to='people.doctor')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(help_text='Parent pregnancy. CASCADE — vaccinations deleted with pregnancy.', on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pregnancy.pregnancy')),
            ],
            options={
                'verbose_name': 'Vaccination (Maternal)',
                'verbose_name_plural': 'Vaccinations (Maternal)',
                'db_table': 'vaccination',
                'ordering': ['due_week_start', 'vaccine_name'],
                'indexes': [models.Index(fields=['pregnancy', 'status'], name='idx_vaccination_preg_status')],
            },
        ),
        migrations.CreateModel(
            name='PregnancyRiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('event_date', models.DateField(help_text='Date this risk event was recorded / observed.')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Gestational week at which this event occurred.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], db_index=True, help_text='Severity of this risk event: low | moderate | high | critical', max_length=20)),
                ('event_description', models.TextField(help_text="Clinical description of the risk event (e.g. 'GDM detected on oral glucose test').")),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(help_text='Parent pregnancy. CASCADE — risk events deleted with pregnancy.', on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='pregnancy.pregnancy')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this risk event. SET NULL if user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregnancy Risk Event',
                'verbose_name_plural': 'Pregnancy Risk Events',
                'db_table': 'pregnancy_risk_event',
                'ordering': ['-event_date', '-week_number'],
                'indexes': [models.Index(fields=['pregnancy', 'event_date'], name='idx_risk_event_preg_date'), models.Index(fields=['risk_level'], name='idx_risk_event_level')],
            },
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['patient', 'is_active'], name='idx_pregnancy_patient_active'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['risk_status', 'is_active'], name='idx_pregnancy_risk_active'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['is_deleted'], name='idx_pregnancy_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['assigned_doctor'], name='idx_pregnancy_doctor'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.CheckConstraint(check=models.Q(('edd__gt', models.F('lmp'))), name='chk_pregnancy_edd_after_lmp'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.CheckConstraint(check=models.Q(('current_week__gte', 1), ('current_week__lte', 45)), name='chk_pregnancy_week_range'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.CheckConstraint(check=models.Q(('trimester__in', [1, 2, 3])), name='chk_pregnancy_trimester_valid'),
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['pregnancy', 'visit_date'], name='idx_ancvisit_preg_date'),
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['doctor', 'visit_date'], name='idx_ancvisit_doc_date'),
        ),
    ]
