# Generated by Django 4.2.30 on 2026-06-07 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('delivery_datetime', models.DateTimeField()),
                ('delivery_mode', models.CharField(choices=[('normal', 'Normal'), ('c_section', 'C-Section'), ('assisted', 'Assisted'), ('water_birth', 'Water Birth')], max_length=20)),
                ('blood_loss_ml', models.IntegerField(blank=True, help_text='Total estimated blood loss in ml.', null=True)),
                ('placenta_complete', models.BooleanField(default=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery', to='admissions.admission')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='people.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='people.patient')),
            ],
            options={
                'db_table': 'delivery',
                'ordering': ['-delivery_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('procedure_name', models.CharField(help_text='Name of the procedure, e.g. Caesarean Section.', max_length=120)),
                ('indication', models.TextField(blank=True)),
                ('technique', models.TextField(blank=True)),
                ('implants_used', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Duration in minutes.')),
                ('post_op_instructions', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='procedures', to='delivery.delivery')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='people.doctor')),
            ],
            options={
                'db_table': 'delivery_procedure',
                'ordering': ['-performed_at'],
            },
        ),
    ]
