# Generated by Django 4.2.30 on 2026-06-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when prescription was issued (typically when consultation completes).')),
                ('notes', models.TextField(blank=True, help_text='General notes for the prescription (e.g. special instructions, pharmacist notes).')),
                ('consultation', models.ForeignKey(help_text='Source consultation. RESTRICT: cannot delete consultation that has prescriptions.', on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this prescription belongs to. Denormalised from consultation.', on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='people.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescription',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('dosage', models.CharField(help_text='Dose per administration: e.g. 500mg, 1 tablet, 5ml.', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily (OD)'), ('BD', 'Twice Daily (BD)'), ('TDS', 'Three Times Daily (TDS)'), ('QID', 'Four Times Daily (QID)'), ('SOS', 'As Needed (SOS)'), ('STAT', 'Immediately (STAT)'), ('weekly', 'Weekly')], help_text='Administration frequency: OD, BD, TDS, QID, SOS, STAT, Weekly.', max_length=20)),
                ('duration', models.CharField(help_text='Treatment duration: e.g. 7 days, 30 days, Ongoing.', max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions: take after food, avoid sun exposure, etc.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the prescription. Lower numbers displayed first.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(help_text='Medicine from formulary. No free-text allowed (BR-RX-03).', on_delete=django.db.models.deletion.RESTRICT, related_name='prescription_items', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(help_text='Parent prescription. CASCADE: items deleted if prescription deleted (admin only).', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'db_table': 'prescription_item',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['prescription'], name='idx_rx_item_prescription'), models.Index(fields=['medicine'], name='idx_rx_item_medicine')],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'issued_at'], name='idx_rx_patient_issued'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='idx_rx_consultation'),
        ),
    ]
