# Generated by Django 4.2.30 on 2026-06-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='The doctor who issued this prescription.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='people.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('dispensed', 'Dispensed')], default='saved', help_text='Status of the prescription.', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration in integer days.', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity_to_dispense',
            field=models.IntegerField(default=1, help_text='Total unit quantity to dispense.'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, help_text='Route of administration (e.g. Oral, IV, IM, Topical).', max_length=50),
        ),
    ]
