# Generated by Django 4.2.30 on 2026-06-07 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newborn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('baby_mrn', models.CharField(help_text='Newborn unique identifier in NB-YYYY-XXX format.', max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undetermined')], max_length=2)),
                ('birth_weight_kg', models.DecimalField(decimal_places=3, help_text='Birth weight in kg.', max_digits=5)),
                ('birth_length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Birth length in cm.', max_digits=5, null=True)),
                ('apgar_1min', models.IntegerField()),
                ('apgar_5min', models.IntegerField()),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('nicu_required', 'NICU Required'), ('deceased', 'Deceased'), ('transferred', 'Transferred')], default='healthy', max_length=20)),
                ('nicu_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='newborns', to='delivery.delivery')),
            ],
            options={
                'db_table': 'newborn',
                'ordering': ['baby_mrn'],
            },
        ),
        migrations.CreateModel(
            name='NewbornVital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=5)),
                ('head_circ_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius.', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newborn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='newborn.newborn')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newborn_vital',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewbornVaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('due', 'Due'), ('administered', 'Administered'), ('not_required', 'Not Required'), ('skipped', 'Skipped')], default='due', max_length=20)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newborn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='newborn.newborn')),
            ],
            options={
                'db_table': 'newborn_vaccination',
                'ordering': ['vaccine_name', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='NewbornFeedingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('feed_type', models.CharField(choices=[('breast', 'Breast'), ('formula', 'Formula'), ('ng_tube', 'NG Tube'), ('iv', 'IV')], max_length=20)),
                ('feed_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Required for formula/ng/iv.', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newborn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='newborn.newborn')),
            ],
            options={
                'db_table': 'newborn_feeding_log',
                'ordering': ['-feed_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='newborn',
            constraint=models.CheckConstraint(check=models.Q(('apgar_1min__range', (0, 10))), name='chk_newborn_apgar_1min_0_10'),
        ),
        migrations.AddConstraint(
            model_name='newborn',
            constraint=models.CheckConstraint(check=models.Q(('apgar_5min__range', (0, 10))), name='chk_newborn_apgar_5min_0_10'),
        ),
    ]
