"""
MotherCare — People Module Serializers
Architecture: CLAUDE.md — "One serializer per action where shapes differ"

Serializer hierarchy per model:
    Patient     → PatientListSerializer, PatientDetailSerializer, PatientWriteSerializer
    EmergencyContact → EmergencyContactSerializer
    PatientEmergencyContact → PatientEmergencyContactSerializer, PatientEmergencyContactWriteSerializer
    PatientAllergy → PatientAllergySerializer, PatientAllergyWriteSerializer
    Staff       → StaffListSerializer, StaffDetailSerializer, StaffWriteSerializer
    Doctor      → DoctorListSerializer, DoctorDetailSerializer, DoctorWriteSerializer
"""
from datetime import date

from rest_framework import serializers

from apps.people.constants import BLOCKING_ALLERGY_SEVERITIES
from apps.people.models import (
    Doctor,
    EmergencyContact,
    Patient,
    PatientAllergy,
    PatientEmergencyContact,
    Staff,
)


# ─────────────────────────────────────────────────────────────────────────────
# Patient Serializers
# ─────────────────────────────────────────────────────────────────────────────
class PatientListSerializer(serializers.ModelSerializer):
    """Compact list representation for the patient roster."""

    age = serializers.SerializerMethodField()

    class Meta:
        model = Patient
        fields = [
            "id",
            "mrn",
            "full_name",
            "dob",
            "age",
            "blood_group",
            "phone",
            "is_active",
            "created_at",
        ]
        read_only_fields = fields

    def get_age(self, obj: Patient) -> int | None:
        """Calculate age from DOB."""
        if not obj.dob:
            return None
        today = date.today()
        return today.year - obj.dob.year - (
            (today.month, today.day) < (obj.dob.month, obj.dob.day)
        )


class PatientDetailSerializer(serializers.ModelSerializer):
    """Full patient profile including computed fields."""

    age = serializers.SerializerMethodField()
    allergy_count = serializers.SerializerMethodField()
    has_blocking_allergies = serializers.SerializerMethodField()
    primary_contact = serializers.SerializerMethodField()

    class Meta:
        model = Patient
        fields = [
            "id",
            "mrn",
            "full_name",
            "dob",
            "age",
            "blood_group",
            "phone",
            "alt_phone",
            "email",
            "address",
            "is_active",
            "is_deleted",
            "deleted_at",
            "allergy_count",
            "has_blocking_allergies",
            "primary_contact",
            "created_at",
            "updated_at",
            "created_by",
        ]
        read_only_fields = fields

    def get_age(self, obj: Patient) -> int | None:
        if not obj.dob:
            return None
        today = date.today()
        return today.year - obj.dob.year - (
            (today.month, today.day) < (obj.dob.month, obj.dob.day)
        )

    def get_allergy_count(self, obj: Patient) -> int:
        return obj.allergies.count()

    def get_has_blocking_allergies(self, obj: Patient) -> bool:
        """True if the patient has any severe or life-threatening allergies (BR-RX-05)."""
        return obj.allergies.filter(severity__in=list(BLOCKING_ALLERGY_SEVERITIES)).exists()

    def get_primary_contact(self, obj: Patient) -> dict | None:
        link = (
            obj.emergency_contacts
            .select_related("contact")
            .filter(is_primary=True)
            .first()
        )
        if not link:
            return None
        return {
            "name": link.contact.name,
            "phone": link.contact.phone,
            "relationship_type": link.relationship_type,
        }


class PatientWriteSerializer(serializers.ModelSerializer):
    """Write serializer for patient create/update. MRN is generated by service layer."""

    class Meta:
        model = Patient
        fields = [
            "full_name",
            "dob",
            "blood_group",
            "phone",
            "alt_phone",
            "email",
            "address",
            "is_active",
        ]

    def validate_dob(self, value: date) -> date:
        """DOB must be in the past (patients are not unborn)."""
        if value >= date.today():
            raise serializers.ValidationError("Date of birth must be in the past.")
        return value

    def validate_phone(self, value: str) -> str:
        """Phone number must not already exist on another active patient."""
        qs = Patient.objects.filter(phone=value)
        if self.instance:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise serializers.ValidationError(
                "A patient with this phone number already exists."
            )
        return value


# ─────────────────────────────────────────────────────────────────────────────
# EmergencyContact Serializers
# ─────────────────────────────────────────────────────────────────────────────
class EmergencyContactSerializer(serializers.ModelSerializer):
    """Read/write serializer for EmergencyContact (standalone)."""

    class Meta:
        model = EmergencyContact
        fields = ["id", "name", "phone", "alt_phone", "email", "created_at"]
        read_only_fields = ["id", "created_at"]


# ─────────────────────────────────────────────────────────────────────────────
# PatientEmergencyContact Serializers
# ─────────────────────────────────────────────────────────────────────────────
class PatientEmergencyContactSerializer(serializers.ModelSerializer):
    """Read serializer for a patient's emergency contacts (nested under patient)."""

    contact = EmergencyContactSerializer(read_only=True)

    class Meta:
        model = PatientEmergencyContact
        fields = [
            "id",
            "contact",
            "relationship_type",
            "priority",
            "is_primary",
            "created_at",
        ]
        read_only_fields = fields


class PatientEmergencyContactWriteSerializer(serializers.ModelSerializer):
    """Write serializer: add/link an emergency contact to a patient."""

    # Allow creating a new contact inline or referencing existing by ID
    contact_id = serializers.UUIDField(
        required=False,
        help_text="UUID of an existing EmergencyContact to link.",
    )
    name = serializers.CharField(
        required=False, write_only=True,
        help_text="Name for a new EmergencyContact (used when contact_id is not provided).",
    )
    phone = serializers.CharField(
        required=False, write_only=True,
        help_text="Phone for a new EmergencyContact.",
    )
    alt_phone = serializers.CharField(
        required=False, write_only=True, allow_blank=True,
    )
    email = serializers.EmailField(
        required=False, write_only=True, allow_blank=True,
    )

    class Meta:
        model = PatientEmergencyContact
        fields = [
            "contact_id",
            "name",
            "phone",
            "alt_phone",
            "email",
            "relationship_type",
            "priority",
        ]

    def validate(self, attrs: dict) -> dict:
        """Must provide either contact_id (existing) or name+phone (new)."""
        contact_id = attrs.get("contact_id")
        name = attrs.get("name")
        phone = attrs.get("phone")

        if not contact_id and not (name and phone):
            raise serializers.ValidationError(
                "Provide either 'contact_id' (existing contact) or "
                "'name' and 'phone' (new contact)."
            )
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# PatientAllergy Serializers
# ─────────────────────────────────────────────────────────────────────────────
class PatientAllergySerializer(serializers.ModelSerializer):
    """Read serializer for a patient allergy."""

    is_blocking = serializers.SerializerMethodField()

    class Meta:
        model = PatientAllergy
        fields = [
            "id",
            "allergen",
            "reaction_type",
            "severity",
            "is_blocking",
            "recorded_date",
            "recorded_by",
            "notes",
            "created_at",
        ]
        read_only_fields = fields

    def get_is_blocking(self, obj: PatientAllergy) -> bool:
        """True if this allergy triggers a blocking alert at prescription time (BR-RX-05)."""
        return obj.severity in BLOCKING_ALLERGY_SEVERITIES


class PatientAllergyWriteSerializer(serializers.ModelSerializer):
    """Write serializer for recording a new allergy."""

    class Meta:
        model = PatientAllergy
        fields = [
            "allergen",
            "reaction_type",
            "severity",
            "recorded_date",
            "notes",
        ]

    def validate_recorded_date(self, value: date) -> date:
        if value > date.today():
            raise serializers.ValidationError("Recorded date cannot be in the future.")
        return value


# ─────────────────────────────────────────────────────────────────────────────
# Staff Serializers
# ─────────────────────────────────────────────────────────────────────────────
class StaffListSerializer(serializers.ModelSerializer):
    """Compact staff list representation."""

    department_name = serializers.CharField(
        source="department.name", read_only=True, default=None,
    )
    has_doctor_profile = serializers.SerializerMethodField()

    class Meta:
        model = Staff
        fields = [
            "id",
            "full_name",
            "designation",
            "department_name",
            "phone",
            "is_active",
            "join_date",
            "has_doctor_profile",
        ]
        read_only_fields = fields

    def get_has_doctor_profile(self, obj: Staff) -> bool:
        return hasattr(obj, "doctor_profile")


class StaffDetailSerializer(serializers.ModelSerializer):
    """Full staff profile."""

    department_name = serializers.CharField(
        source="department.name", read_only=True, default=None,
    )
    doctor_profile = serializers.SerializerMethodField()
    user_username = serializers.CharField(
        source="user.username", read_only=True, default=None,
    )

    class Meta:
        model = Staff
        fields = [
            "id",
            "full_name",
            "designation",
            "department",
            "department_name",
            "user",
            "user_username",
            "phone",
            "email",
            "join_date",
            "is_active",
            "doctor_profile",
            "created_at",
            "updated_at",
            "created_by",
        ]
        read_only_fields = fields

    def get_doctor_profile(self, obj: Staff) -> dict | None:
        if not hasattr(obj, "doctor_profile"):
            return None
        doctor = obj.doctor_profile
        return {
            "id": str(doctor.id),
            "specialisation": doctor.specialisation,
            "registration_no": doctor.registration_no,
            "available_from": doctor.available_from,
            "available_to": doctor.available_to,
        }


class StaffWriteSerializer(serializers.ModelSerializer):
    """Write serializer for creating/updating a staff member."""

    class Meta:
        model = Staff
        fields = [
            "user",
            "department",
            "full_name",
            "designation",
            "phone",
            "email",
            "join_date",
            "is_active",
        ]

    def validate_join_date(self, value: date) -> date:
        if value > date.today():
            raise serializers.ValidationError("Join date cannot be in the future.")
        return value


# ─────────────────────────────────────────────────────────────────────────────
# Doctor Serializers
# ─────────────────────────────────────────────────────────────────────────────
class DoctorListSerializer(serializers.ModelSerializer):
    """Compact doctor list for appointment booking dropdowns."""

    full_name = serializers.CharField(source="staff.full_name", read_only=True)
    department_name = serializers.CharField(
        source="staff.department.name", read_only=True, default=None,
    )
    is_active = serializers.BooleanField(source="staff.is_active", read_only=True)

    class Meta:
        model = Doctor
        fields = [
            "id",
            "full_name",
            "specialisation",
            "registration_no",
            "department_name",
            "available_from",
            "available_to",
            "is_active",
        ]
        read_only_fields = fields


class DoctorDetailSerializer(serializers.ModelSerializer):
    """Full doctor profile including linked staff details."""

    staff_detail = StaffDetailSerializer(source="staff", read_only=True)

    class Meta:
        model = Doctor
        fields = [
            "id",
            "staff",
            "staff_detail",
            "specialisation",
            "registration_no",
            "available_from",
            "available_to",
            "created_at",
            "updated_at",
            "created_by",
        ]
        read_only_fields = fields


class DoctorWriteSerializer(serializers.ModelSerializer):
    """Write serializer for creating/updating a doctor credential."""

    class Meta:
        model = Doctor
        fields = [
            "staff",
            "specialisation",
            "registration_no",
            "available_from",
            "available_to",
        ]

    def validate(self, attrs: dict) -> dict:
        """available_from must be before available_to if both are provided."""
        available_from = attrs.get("available_from")
        available_to = attrs.get("available_to")
        if available_from and available_to and available_from >= available_to:
            raise serializers.ValidationError(
                {"available_to": "available_to must be after available_from."}
            )
        return attrs

    def validate_staff(self, staff: Staff) -> Staff:
        """A Doctor profile cannot be created for the same staff member twice."""
        qs = Doctor.objects.filter(staff=staff)
        if self.instance:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise serializers.ValidationError(
                "A Doctor profile already exists for this staff member."
            )
        return staff
