# Generated by Django 4.2.30 on 2026-06-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('name', models.CharField(help_text='Brand/generic drug name.', max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='INN generic name (e.g., Paracetamol for Calpol).', max_length=255)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup / Suspension'), ('injection', 'Injection'), ('topical', 'Topical / Ointment'), ('inhaler', 'Inhaler'), ('drops', 'Drops (Eye/Ear/Nasal)'), ('suppository', 'Suppository'), ('patch', 'Transdermal Patch'), ('powder', 'Powder / Sachet'), ('other', 'Other')], default='tablet', help_text='Dosage form.', max_length=30)),
                ('unit', models.CharField(default='tablet', help_text='Dispensing unit: tablet, ml, sachet, etc.', max_length=50)),
                ('reorder_level', models.PositiveIntegerField(default=50, help_text='Minimum stock quantity before reorder alert is triggered.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive medicines cannot be prescribed (BR-PHARM-01).')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'medicine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('batch_number', models.CharField(help_text='Supplier batch/lot number.', max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity. Must be >= 0. Use SELECT FOR UPDATE before decrement.')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Medicine Batch',
                'verbose_name_plural': 'Medicine Batches',
                'db_table': 'medicine_batch',
                'ordering': ['expiry_date', 'purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pharmacy_sales', to='people.patient')),
            ],
            options={
                'verbose_name': 'Pharmacy Sale',
                'verbose_name_plural': 'Pharmacy Sales',
                'db_table': 'pharmacy_sale',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed: qty * unit_price. Stored for audit immutability.', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine_batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_items', to='pharmacy.medicinebatch')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacysale')),
            ],
            options={
                'verbose_name': 'Pharmacy Sale Item',
                'verbose_name_plural': 'Pharmacy Sale Items',
                'db_table': 'pharmacy_sale_item',
            },
        ),
    ]
