# Generated by Django 4.2.30 on 2026-06-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batches', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pharmacysaleitem',
            constraint=models.CheckConstraint(check=models.Q(('qty__gt', 0)), name='chk_sale_item_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['patient'], name='idx_sale_patient'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['sold_at'], name='idx_sale_sold_at'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='idx_batch_medicine_expiry'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='uq_batch_medicine_batch_no'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('expiry_date__gt', models.F('purchase_date'))), name='chk_batch_expiry_after_purchase'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='idx_medicine_active'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='idx_medicine_category'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='uq_medicine_name_category'),
        ),
    ]
