# Generated by Django 4.2.30 on 2026-06-07 06:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('name', models.CharField(help_text='Full name of the emergency contact.', max_length=255)),
                ('phone', models.CharField(help_text='Primary phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, -, spaces, parentheses).', regex='^\\+?[\\d\\s\\-().]{7,20}$')])),
                ('alt_phone', models.CharField(blank=True, help_text='Alternate phone number (optional).', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, -, spaces, parentheses).', regex='^\\+?[\\d\\s\\-().]{7,20}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional).', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'emergency_contact',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('mrn', models.CharField(db_index=True, help_text='Medical Record Number. Auto-generated. Format: PT-XXXX-A. Never manually assigned.', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the patient (BR-PAT-03: mandatory).', max_length=255)),
                ('dob', models.DateField(help_text='Date of birth (BR-PAT-03: mandatory).')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='ABO/Rh blood group (BR-PAT-03: mandatory).', max_length=10)),
                ('phone', models.CharField(db_index=True, help_text='Primary phone number (BR-PAT-03: mandatory, BR-PAT-07: searchable).', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, -, spaces, parentheses).', regex='^\\+?[\\d\\s\\-().]{7,20}$')])),
                ('alt_phone', models.CharField(blank=True, help_text='Alternate phone number (optional).', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, -, spaces, parentheses).', regex='^\\+?[\\d\\s\\-().]{7,20}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional).', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Residential address (optional).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this patient is currently active.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('full_name', models.CharField(help_text='Full name of the staff member.', max_length=255)),
                ('designation', models.CharField(help_text='Job title or designation (e.g. Nurse, Lab Technician, Receptionist).', max_length=100)),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, may include +, -, spaces, parentheses).', regex='^\\+?[\\d\\s\\-().]{7,20}$')])),
                ('email', models.EmailField(blank=True, help_text='Work email address (optional).', max_length=254)),
                ('join_date', models.DateField(help_text='Date of joining the hospital.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active/Inactive status. Inactive staff cannot be assigned to new appointments.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department this staff member belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hospital_config.department')),
                ('user', models.OneToOneField(blank=True, help_text='System login account. NULL if this staff member has no system access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], help_text='Relationship of this contact to the patient.', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(help_text='Priority order. 1 = primary contact. Lower number = higher priority.')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Denormalised flag: True when priority = 1. Managed automatically.')),
                ('contact', models.ForeignKey(help_text='The emergency contact record.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='people.emergencycontact')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient this contact is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='people.patient')),
            ],
            options={
                'verbose_name': 'Patient Emergency Contact',
                'verbose_name_plural': 'Patient Emergency Contacts',
                'db_table': 'patient_emergency_contact',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('allergen', models.CharField(help_text='Name of the allergen (e.g. medicine generic name, food, latex).', max_length=200)),
                ('reaction_type', models.CharField(blank=True, help_text='Observed reaction (e.g. hives, anaphylaxis, rash).', max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], help_text="Severity level. 'severe' and 'life_threatening' trigger blocking alerts (BR-RX-05).", max_length=20)),
                ('recorded_date', models.DateField(help_text='Date this allergy was recorded.')),
                ('notes', models.TextField(blank=True, help_text='Additional clinical notes.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient who has this allergy.', on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='people.patient')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this allergy entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'db_table': 'patient_allergy',
                'ordering': ['-severity', '-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('specialisation', models.CharField(help_text='Medical specialisation (e.g. Obstetrics, Gynecology, Pediatrics).', max_length=200)),
                ('registration_no', models.CharField(db_index=True, help_text='Medical council registration number. Must be unique. Architecture: UNIQUE(registration_no).', max_length=50, unique=True)),
                ('available_from', models.TimeField(blank=True, help_text="Start of the doctor's availability window (TIME, nullable for on-call doctors).", null=True)),
                ('available_to', models.TimeField(blank=True, help_text="End of the doctor's availability window (TIME, nullable for on-call doctors).", null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(help_text='The staff record this doctor credential is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='people.staff')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctor',
                'ordering': ['staff__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='idx_staff_active'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department', 'is_active'], name='idx_staff_dept_active'),
        ),
        migrations.AddIndex(
            model_name='patientemergencycontact',
            index=models.Index(fields=['patient', 'priority'], name='idx_patient_ec_priority'),
        ),
        migrations.AddConstraint(
            model_name='patientemergencycontact',
            constraint=models.CheckConstraint(check=models.Q(('priority__gt', 0)), name='chk_patient_ec_priority_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='patientemergencycontact',
            unique_together={('patient', 'contact')},
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient', 'allergen'], name='idx_allergy_patient_allergen'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient', 'severity'], name='idx_allergy_patient_severity'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mrn'], name='idx_patient_mrn'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='idx_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='idx_patient_name'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['is_deleted', 'is_active'], name='idx_patient_active_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['registration_no'], name='idx_doctor_reg_no'),
        ),
    ]
