# Generated by Django 4.2.30 on 2026-06-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TRUE = logically deleted. Use soft_delete() method.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion (UTC). NULL if not deleted.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharge_pending', 'Discharge Pending'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], db_index=True, default='active', help_text='Clinical state of the admission.', max_length=20)),
                ('admission_type', models.CharField(choices=[('maternity', 'Maternity'), ('post_natal', 'Post Natal'), ('emergency', 'Emergency'), ('surgery', 'Surgery')], help_text='Type of admission.', max_length=20)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_discharge', models.DateTimeField(blank=True, help_text='Estimated discharge date and time.', null=True)),
                ('actual_discharge', models.DateTimeField(blank=True, help_text='Actual discharge date and time.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admission',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('bed_number', models.CharField(help_text='Unique identifier for the bed.', max_length=50, unique=True)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('private', 'Private'), ('labor', 'Labor'), ('nicu', 'NICU'), ('icu', 'ICU')], help_text='Type of ward.', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], db_index=True, default='available', help_text='Real-time status of the bed.', max_length=20)),
                ('floor', models.IntegerField(default=1, help_text='Floor number.')),
                ('last_cleaned_at', models.DateTimeField(blank=True, help_text='When the bed was last cleaned.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bed',
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='WardTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='admissions.admission')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='admissions.bed')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_to', to='admissions.bed')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ward_transfer',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='admissions.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='people.doctor'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='people.patient'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(check=models.Q(('actual_discharge__isnull', True), ('actual_discharge__gt', models.F('admitted_at')), _connector='OR'), name='chk_admission_discharge_after_admitted'),
        ),
    ]
