# Generated by Django 4.2.30 on 2026-06-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('test_type', models.CharField(choices=[('cbc', 'Complete Blood Count (CBC)'), ('blood_group', 'Blood Group & Rh Typing'), ('hba1c', 'HbA1c'), ('glucose_fasting', 'Fasting Glucose'), ('glucose_pp', 'Post-Prandial Glucose'), ('ogtt', 'OGTT (Oral Glucose Tolerance)'), ('urine_routine', 'Urine Routine'), ('urine_culture', 'Urine Culture & Sensitivity'), ('thyroid', 'Thyroid Function (TSH/T3/T4)'), ('liver_function', 'Liver Function Test (LFT)'), ('kidney_function', 'Kidney Function Test (KFT)'), ('serum_ferritin', 'Serum Ferritin'), ('vitamin_d', 'Vitamin D (25-OH)'), ('vdrl', 'VDRL/RPR'), ('hiv', 'HIV Screening'), ('hbsag', 'HBsAg'), ('hcv', 'HCV Antibody'), ('torch', 'TORCH Panel'), ('anomaly_scan', 'Anomaly Scan (USG)'), ('nt_scan', 'NT Scan (Nuchal Translucency)'), ('growth_scan', 'Growth Scan (USG)'), ('doppler', 'Doppler Study'), ('other', 'Other')], help_text='Type of lab test. Must be from the standard test type list.', max_length=30)),
                ('urgency', models.CharField(choices=[('stat', 'STAT (Immediate)'), ('urgent', 'Urgent'), ('routine', 'Routine')], db_index=True, default='routine', help_text='Priority: stat (immediate) > urgent > routine. [BR-LAB-03]', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('critical', 'Critical')], db_index=True, default='pending', help_text='Lab test lifecycle status.', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the test was ordered.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When results were ready. Set automatically on completion.', null=True)),
                ('key_findings', models.TextField(blank=True, help_text='Summary of lab findings populated by lab technician when completing.')),
                ('flagged', models.BooleanField(db_index=True, default=False, help_text='Set True when results require immediate clinical attention. Auto-set when status = critical. [BR-LAB-02]')),
                ('consultation', models.ForeignKey(blank=True, help_text='Optional — test may be ordered outside a consultation. [BR-LAB-04]', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lab_tests', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(help_text='Doctor who ordered this test.', on_delete=django.db.models.deletion.RESTRICT, related_name='ordered_lab_tests', to='people.doctor')),
                ('patient', models.ForeignKey(help_text='Patient this test belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='lab_tests', to='people.patient')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'db_table': 'lab_test',
                'ordering': ['urgency', '-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('file_url', models.CharField(help_text='Full URL to uploaded file (S3 presigned URL or local media path).', max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPEG Image'), ('png', 'PNG Image'), ('dicom', 'DICOM')], default='pdf', help_text='File format: pdf, jpg, png, dicom.', max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this file was uploaded.')),
                ('notes', models.TextField(blank=True, help_text='Lab technician notes about this specific report upload.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lab_test', models.ForeignKey(help_text='Parent lab test. CASCADE: files follow the test lifecycle.', on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='laboratory.labtest')),
                ('uploaded_by', models.ForeignKey(help_text='User (lab tech/admin) who uploaded this file.', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Report File',
                'verbose_name_plural': 'Lab Report Files',
                'db_table': 'lab_report_file',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['patient', 'status'], name='idx_labtest_patient_status'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['urgency', 'status'], name='idx_labtest_urgency_status'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['flagged'], name='idx_labtest_flagged'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['ordered_by'], name='idx_labtest_doctor'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['consultation'], name='idx_labtest_consultation'),
        ),
        migrations.AddIndex(
            model_name='labreportfile',
            index=models.Index(fields=['lab_test'], name='idx_labfile_test'),
        ),
    ]
