# Generated by Django 4.2.30 on 2026-06-15 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Status of the overall lab order.', max_length=20)),
                ('clinical_note', models.TextField(blank=True, help_text='Clinical indications/notes provided by ordering doctor.')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the lab order was placed.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the last result was completed.', null=True)),
                ('consultation', models.ForeignKey(blank=True, help_text='Consultation from which this order originated.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lab_orders', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor who ordered these tests.', on_delete=django.db.models.deletion.RESTRICT, related_name='lab_orders', to='people.doctor')),
                ('patient', models.ForeignKey(help_text='Patient this lab order belongs to.', on_delete=django.db.models.deletion.RESTRICT, related_name='lab_orders', to='people.patient')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'db_table': 'lab_order',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='TestMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('name', models.CharField(help_text='Name of the laboratory test.', max_length=255)),
                ('code', models.CharField(help_text='Unique test code (e.g. CBC, BG).', max_length=50, unique=True)),
                ('category', models.CharField(help_text='Category of the test (e.g. Hematology, Biochemistry).', max_length=100)),
                ('normal_range', models.CharField(blank=True, help_text='Reference/normal range.', max_length=255)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g. g/dL, mg/dL).', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Standard cost of the test.', max_digits=10)),
                ('turnaround_hours', models.PositiveIntegerField(default=24, help_text='Standard turnaround time in hours.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this test type is currently active.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Master',
                'verbose_name_plural': 'Test Masters',
                'db_table': 'lab_test_master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('report_file', models.FileField(help_text='Uploaded PDF report document.', upload_to='lab_reports/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the report file was uploaded.')),
                ('doctor_comment', models.TextField(blank=True, help_text='Annotation or feedback comment added by doctor.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when reviewed by doctor.', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(help_text='Related lab order.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='laboratory.laborder')),
                ('uploaded_by', models.ForeignKey(help_text='Staff user who uploaded this report.', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'db_table': 'lab_report',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — never expose raw to client without masking.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp (UTC). Set once, never modified.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UTC). Auto-updated on every save().')),
                ('result_value', models.CharField(blank=True, help_text='Recorded test result value.', max_length=255)),
                ('result_note', models.TextField(blank=True, help_text='Additional observations, notes or findings from technician.')),
                ('is_abnormal', models.BooleanField(db_index=True, default=False, help_text='True if result value falls outside normal range or is flagged abnormal.')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='User who created this record. NULL for system-generated rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(help_text='Parent lab order.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('test', models.ForeignKey(help_text='The specific test type.', on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='laboratory.testmaster')),
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
                'db_table': 'lab_order_item',
            },
        ),
    ]
